# Generated by Django 5.0.1 on 2024-02-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='Product_subcategory',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womans', 'Womans'), ('Kids', 'Kids')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='Product_category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Sportswear', 'Sportswear'), ('Jumpsuits', 'Jumpsuits'), ('Blazers', 'Blazers'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Kurthas', 'Kurthas')], max_length=255),
        ),
    ]
