# Generated by Django 5.0.1 on 2024-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_checkoutaddress_cartitems_checkoutaaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
