# Generated by Django 5.0.1 on 2024-02-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_checkoutaddress_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='checkoutaaddress',
        ),
        migrations.AddField(
            model_name='checkoutitems',
            name='checkoutaaddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.checkoutaddress'),
        ),
    ]
