# Generated by Django 5.0.6 on 2024-12-29 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='Product_category',
            field=models.CharField(choices=[('Bricks', 'Bricks'), ('Cement', 'Cement'), ('Sand', 'Sand'), ('Steel', 'Steel'), ('Tiles', 'Tiles'), ('Paint', 'Paint'), ('Wood', 'Wood'), ('Glass', 'Glass'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Roofing', 'Roofing'), ('Doors', 'Doors'), ('Windows', 'Windows'), ('Hardware', 'Hardware'), ('Insulation', 'Insulation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='Product_subcategory',
            field=models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Bathroom', 'Bathroom'), ('Kitchen', 'Kitchen'), ('Roofing', 'Roofing'), ('Flooring', 'Flooring'), ('Foundation', 'Foundation'), ('Walls', 'Walls')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('disposal', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Product.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Product.servicecategory'),
        ),
    ]
